package org.aes.cipher;

import com.google.common.primitives.UnsignedBytes;

public class SBox {
    public static final byte[][] SBOX = {
            {
                    UnsignedBytes.parseUnsignedByte("63", 16),
                    UnsignedBytes.parseUnsignedByte("7c", 16),
                    UnsignedBytes.parseUnsignedByte("77", 16),
                    UnsignedBytes.parseUnsignedByte("7b", 16),
                    UnsignedBytes.parseUnsignedByte("f2", 16),
                    UnsignedBytes.parseUnsignedByte("6b", 16),
                    UnsignedBytes.parseUnsignedByte("6f", 16),
                    UnsignedBytes.parseUnsignedByte("c5", 16),
                    UnsignedBytes.parseUnsignedByte("30", 16),
                    UnsignedBytes.parseUnsignedByte("01", 16),
                    UnsignedBytes.parseUnsignedByte("67", 16),
                    UnsignedBytes.parseUnsignedByte("2b", 16),
                    UnsignedBytes.parseUnsignedByte("fe", 16),
                    UnsignedBytes.parseUnsignedByte("d7", 16),
                    UnsignedBytes.parseUnsignedByte("ab", 16),
                    UnsignedBytes.parseUnsignedByte("76", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("ca", 16),
                    UnsignedBytes.parseUnsignedByte("82", 16),
                    UnsignedBytes.parseUnsignedByte("c9", 16),
                    UnsignedBytes.parseUnsignedByte("7d", 16),
                    UnsignedBytes.parseUnsignedByte("fa", 16),
                    UnsignedBytes.parseUnsignedByte("59", 16),
                    UnsignedBytes.parseUnsignedByte("47", 16),
                    UnsignedBytes.parseUnsignedByte("f0", 16),
                    UnsignedBytes.parseUnsignedByte("ad", 16),
                    UnsignedBytes.parseUnsignedByte("d4", 16),
                    UnsignedBytes.parseUnsignedByte("a2", 16),
                    UnsignedBytes.parseUnsignedByte("af", 16),
                    UnsignedBytes.parseUnsignedByte("9c", 16),
                    UnsignedBytes.parseUnsignedByte("a4", 16),
                    UnsignedBytes.parseUnsignedByte("72", 16),
                    UnsignedBytes.parseUnsignedByte("c0", 16)

            },
            {
                    UnsignedBytes.parseUnsignedByte("b7", 16),
                    UnsignedBytes.parseUnsignedByte("fd", 16),
                    UnsignedBytes.parseUnsignedByte("93", 16),
                    UnsignedBytes.parseUnsignedByte("26", 16),
                    UnsignedBytes.parseUnsignedByte("36", 16),
                    UnsignedBytes.parseUnsignedByte("3f", 16),
                    UnsignedBytes.parseUnsignedByte("f7", 16),
                    UnsignedBytes.parseUnsignedByte("cc", 16),
                    UnsignedBytes.parseUnsignedByte("34", 16),
                    UnsignedBytes.parseUnsignedByte("a5", 16),
                    UnsignedBytes.parseUnsignedByte("e5", 16),
                    UnsignedBytes.parseUnsignedByte("f1", 16),
                    UnsignedBytes.parseUnsignedByte("71", 16),
                    UnsignedBytes.parseUnsignedByte("d8", 16),
                    UnsignedBytes.parseUnsignedByte("31", 16),
                    UnsignedBytes.parseUnsignedByte("15", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("04", 16),
                    UnsignedBytes.parseUnsignedByte("c7", 16),
                    UnsignedBytes.parseUnsignedByte("23", 16),
                    UnsignedBytes.parseUnsignedByte("c3", 16),
                    UnsignedBytes.parseUnsignedByte("18", 16),
                    UnsignedBytes.parseUnsignedByte("96", 16),
                    UnsignedBytes.parseUnsignedByte("05", 16),
                    UnsignedBytes.parseUnsignedByte("9a", 16),
                    UnsignedBytes.parseUnsignedByte("07", 16),
                    UnsignedBytes.parseUnsignedByte("12", 16),
                    UnsignedBytes.parseUnsignedByte("80", 16),
                    UnsignedBytes.parseUnsignedByte("e2", 16),
                    UnsignedBytes.parseUnsignedByte("eb", 16),
                    UnsignedBytes.parseUnsignedByte("27", 16),
                    UnsignedBytes.parseUnsignedByte("b2", 16),
                    UnsignedBytes.parseUnsignedByte("75", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("09", 16),
                    UnsignedBytes.parseUnsignedByte("83", 16),
                    UnsignedBytes.parseUnsignedByte("2c", 16),
                    UnsignedBytes.parseUnsignedByte("1a", 16),
                    UnsignedBytes.parseUnsignedByte("1b", 16),
                    UnsignedBytes.parseUnsignedByte("6e", 16),
                    UnsignedBytes.parseUnsignedByte("5a", 16),
                    UnsignedBytes.parseUnsignedByte("a0", 16),
                    UnsignedBytes.parseUnsignedByte("52", 16),
                    UnsignedBytes.parseUnsignedByte("3b", 16),
                    UnsignedBytes.parseUnsignedByte("d6", 16),
                    UnsignedBytes.parseUnsignedByte("b3", 16),
                    UnsignedBytes.parseUnsignedByte("29", 16),
                    UnsignedBytes.parseUnsignedByte("e3", 16),
                    UnsignedBytes.parseUnsignedByte("2f", 16),
                    UnsignedBytes.parseUnsignedByte("84", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("53", 16),
                    UnsignedBytes.parseUnsignedByte("d1", 16),
                    UnsignedBytes.parseUnsignedByte("00", 16),
                    UnsignedBytes.parseUnsignedByte("ed", 16),
                    UnsignedBytes.parseUnsignedByte("20", 16),
                    UnsignedBytes.parseUnsignedByte("fc", 16),
                    UnsignedBytes.parseUnsignedByte("b1", 16),
                    UnsignedBytes.parseUnsignedByte("5b", 16),
                    UnsignedBytes.parseUnsignedByte("6a", 16),
                    UnsignedBytes.parseUnsignedByte("cb", 16),
                    UnsignedBytes.parseUnsignedByte("be", 16),
                    UnsignedBytes.parseUnsignedByte("39", 16),
                    UnsignedBytes.parseUnsignedByte("4a", 16),
                    UnsignedBytes.parseUnsignedByte("4c", 16),
                    UnsignedBytes.parseUnsignedByte("58", 16),
                    UnsignedBytes.parseUnsignedByte("cf", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("d0", 16),
                    UnsignedBytes.parseUnsignedByte("ef", 16),
                    UnsignedBytes.parseUnsignedByte("aa", 16),
                    UnsignedBytes.parseUnsignedByte("fb", 16),
                    UnsignedBytes.parseUnsignedByte("43", 16),
                    UnsignedBytes.parseUnsignedByte("4d", 16),
                    UnsignedBytes.parseUnsignedByte("33", 16),
                    UnsignedBytes.parseUnsignedByte("85", 16),
                    UnsignedBytes.parseUnsignedByte("45", 16),
                    UnsignedBytes.parseUnsignedByte("f9", 16),
                    UnsignedBytes.parseUnsignedByte("02", 16),
                    UnsignedBytes.parseUnsignedByte("7f", 16),
                    UnsignedBytes.parseUnsignedByte("50", 16),
                    UnsignedBytes.parseUnsignedByte("3c", 16),
                    UnsignedBytes.parseUnsignedByte("9f", 16),
                    UnsignedBytes.parseUnsignedByte("a8", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("51", 16),
                    UnsignedBytes.parseUnsignedByte("a3", 16),
                    UnsignedBytes.parseUnsignedByte("40", 16),
                    UnsignedBytes.parseUnsignedByte("8f", 16),
                    UnsignedBytes.parseUnsignedByte("92", 16),
                    UnsignedBytes.parseUnsignedByte("9d", 16),
                    UnsignedBytes.parseUnsignedByte("38", 16),
                    UnsignedBytes.parseUnsignedByte("f5", 16),
                    UnsignedBytes.parseUnsignedByte("bc", 16),
                    UnsignedBytes.parseUnsignedByte("b6", 16),
                    UnsignedBytes.parseUnsignedByte("da", 16),
                    UnsignedBytes.parseUnsignedByte("21", 16),
                    UnsignedBytes.parseUnsignedByte("10", 16),
                    UnsignedBytes.parseUnsignedByte("ff", 16),
                    UnsignedBytes.parseUnsignedByte("f3", 16),
                    UnsignedBytes.parseUnsignedByte("d2", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("cd", 16),
                    UnsignedBytes.parseUnsignedByte("0c", 16),
                    UnsignedBytes.parseUnsignedByte("13", 16),
                    UnsignedBytes.parseUnsignedByte("ec", 16),
                    UnsignedBytes.parseUnsignedByte("5f", 16),
                    UnsignedBytes.parseUnsignedByte("97", 16),
                    UnsignedBytes.parseUnsignedByte("44", 16),
                    UnsignedBytes.parseUnsignedByte("17", 16),
                    UnsignedBytes.parseUnsignedByte("c4", 16),
                    UnsignedBytes.parseUnsignedByte("a7", 16),
                    UnsignedBytes.parseUnsignedByte("7e", 16),
                    UnsignedBytes.parseUnsignedByte("3d", 16),
                    UnsignedBytes.parseUnsignedByte("64", 16),
                    UnsignedBytes.parseUnsignedByte("5d", 16),
                    UnsignedBytes.parseUnsignedByte("19", 16),
                    UnsignedBytes.parseUnsignedByte("73", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("60", 16),
                    UnsignedBytes.parseUnsignedByte("81", 16),
                    UnsignedBytes.parseUnsignedByte("4f", 16),
                    UnsignedBytes.parseUnsignedByte("dc", 16),
                    UnsignedBytes.parseUnsignedByte("22", 16),
                    UnsignedBytes.parseUnsignedByte("2a", 16),
                    UnsignedBytes.parseUnsignedByte("90", 16),
                    UnsignedBytes.parseUnsignedByte("88", 16),
                    UnsignedBytes.parseUnsignedByte("46", 16),
                    UnsignedBytes.parseUnsignedByte("ee", 16),
                    UnsignedBytes.parseUnsignedByte("b8", 16),
                    UnsignedBytes.parseUnsignedByte("14", 16),
                    UnsignedBytes.parseUnsignedByte("de", 16),
                    UnsignedBytes.parseUnsignedByte("5e", 16),
                    UnsignedBytes.parseUnsignedByte("0b", 16),
                    UnsignedBytes.parseUnsignedByte("db", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("e0", 16),
                    UnsignedBytes.parseUnsignedByte("32", 16),
                    UnsignedBytes.parseUnsignedByte("3a", 16),
                    UnsignedBytes.parseUnsignedByte("0a", 16),
                    UnsignedBytes.parseUnsignedByte("49", 16),
                    UnsignedBytes.parseUnsignedByte("06", 16),
                    UnsignedBytes.parseUnsignedByte("24", 16),
                    UnsignedBytes.parseUnsignedByte("5c", 16),
                    UnsignedBytes.parseUnsignedByte("c2", 16),
                    UnsignedBytes.parseUnsignedByte("d3", 16),
                    UnsignedBytes.parseUnsignedByte("ac", 16),
                    UnsignedBytes.parseUnsignedByte("62", 16),
                    UnsignedBytes.parseUnsignedByte("91", 16),
                    UnsignedBytes.parseUnsignedByte("95", 16),
                    UnsignedBytes.parseUnsignedByte("e4", 16),
                    UnsignedBytes.parseUnsignedByte("79", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("e7", 16),
                    UnsignedBytes.parseUnsignedByte("c8", 16),
                    UnsignedBytes.parseUnsignedByte("37", 16),
                    UnsignedBytes.parseUnsignedByte("6d", 16),
                    UnsignedBytes.parseUnsignedByte("8d", 16),
                    UnsignedBytes.parseUnsignedByte("d5", 16),
                    UnsignedBytes.parseUnsignedByte("4e", 16),
                    UnsignedBytes.parseUnsignedByte("a9", 16),
                    UnsignedBytes.parseUnsignedByte("6c", 16),
                    UnsignedBytes.parseUnsignedByte("56", 16),
                    UnsignedBytes.parseUnsignedByte("f4", 16),
                    UnsignedBytes.parseUnsignedByte("ea", 16),
                    UnsignedBytes.parseUnsignedByte("65", 16),
                    UnsignedBytes.parseUnsignedByte("7a", 16),
                    UnsignedBytes.parseUnsignedByte("ae", 16),
                    UnsignedBytes.parseUnsignedByte("08", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("ba", 16),
                    UnsignedBytes.parseUnsignedByte("78", 16),
                    UnsignedBytes.parseUnsignedByte("25", 16),
                    UnsignedBytes.parseUnsignedByte("2e", 16),
                    UnsignedBytes.parseUnsignedByte("1c", 16),
                    UnsignedBytes.parseUnsignedByte("a6", 16),
                    UnsignedBytes.parseUnsignedByte("b4", 16),
                    UnsignedBytes.parseUnsignedByte("c6", 16),
                    UnsignedBytes.parseUnsignedByte("e8", 16),
                    UnsignedBytes.parseUnsignedByte("dd", 16),
                    UnsignedBytes.parseUnsignedByte("74", 16),
                    UnsignedBytes.parseUnsignedByte("1f", 16),
                    UnsignedBytes.parseUnsignedByte("4b", 16),
                    UnsignedBytes.parseUnsignedByte("bd", 16),
                    UnsignedBytes.parseUnsignedByte("8b", 16),
                    UnsignedBytes.parseUnsignedByte("8a", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("70", 16),
                    UnsignedBytes.parseUnsignedByte("3e", 16),
                    UnsignedBytes.parseUnsignedByte("b5", 16),
                    UnsignedBytes.parseUnsignedByte("66", 16),
                    UnsignedBytes.parseUnsignedByte("48", 16),
                    UnsignedBytes.parseUnsignedByte("03", 16),
                    UnsignedBytes.parseUnsignedByte("f6", 16),
                    UnsignedBytes.parseUnsignedByte("0e", 16),
                    UnsignedBytes.parseUnsignedByte("61", 16),
                    UnsignedBytes.parseUnsignedByte("35", 16),
                    UnsignedBytes.parseUnsignedByte("57", 16),
                    UnsignedBytes.parseUnsignedByte("b9", 16),
                    UnsignedBytes.parseUnsignedByte("86", 16),
                    UnsignedBytes.parseUnsignedByte("c1", 16),
                    UnsignedBytes.parseUnsignedByte("1d", 16),
                    UnsignedBytes.parseUnsignedByte("9e", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("e1", 16),
                    UnsignedBytes.parseUnsignedByte("f8", 16),
                    UnsignedBytes.parseUnsignedByte("98", 16),
                    UnsignedBytes.parseUnsignedByte("11", 16),
                    UnsignedBytes.parseUnsignedByte("69", 16),
                    UnsignedBytes.parseUnsignedByte("d9", 16),
                    UnsignedBytes.parseUnsignedByte("8e", 16),
                    UnsignedBytes.parseUnsignedByte("94", 16),
                    UnsignedBytes.parseUnsignedByte("9b", 16),
                    UnsignedBytes.parseUnsignedByte("1e", 16),
                    UnsignedBytes.parseUnsignedByte("87", 16),
                    UnsignedBytes.parseUnsignedByte("e9", 16),
                    UnsignedBytes.parseUnsignedByte("ce", 16),
                    UnsignedBytes.parseUnsignedByte("55", 16),
                    UnsignedBytes.parseUnsignedByte("28", 16),
                    UnsignedBytes.parseUnsignedByte("df", 16)
            },
            {
                    UnsignedBytes.parseUnsignedByte("8c", 16),
                    UnsignedBytes.parseUnsignedByte("a1", 16),
                    UnsignedBytes.parseUnsignedByte("89", 16),
                    UnsignedBytes.parseUnsignedByte("0d", 16),
                    UnsignedBytes.parseUnsignedByte("bf", 16),
                    UnsignedBytes.parseUnsignedByte("e6", 16),
                    UnsignedBytes.parseUnsignedByte("42", 16),
                    UnsignedBytes.parseUnsignedByte("68", 16),
                    UnsignedBytes.parseUnsignedByte("41", 16),
                    UnsignedBytes.parseUnsignedByte("99", 16),
                    UnsignedBytes.parseUnsignedByte("2d", 16),
                    UnsignedBytes.parseUnsignedByte("0f", 16),
                    UnsignedBytes.parseUnsignedByte("b0", 16),
                    UnsignedBytes.parseUnsignedByte("54", 16),
                    UnsignedBytes.parseUnsignedByte("bb", 16),
                    UnsignedBytes.parseUnsignedByte("16", 16)
            }
    };

        public static final byte[][] INV_SBOX = {
                {
                        UnsignedBytes.parseUnsignedByte("52", 16),
                        UnsignedBytes.parseUnsignedByte("09", 16),
                        UnsignedBytes.parseUnsignedByte("6a", 16),
                        UnsignedBytes.parseUnsignedByte("d5", 16),
                        UnsignedBytes.parseUnsignedByte("30", 16),
                        UnsignedBytes.parseUnsignedByte("36", 16),
                        UnsignedBytes.parseUnsignedByte("a5", 16),
                        UnsignedBytes.parseUnsignedByte("38", 16),
                        UnsignedBytes.parseUnsignedByte("bf", 16),
                        UnsignedBytes.parseUnsignedByte("40", 16),
                        UnsignedBytes.parseUnsignedByte("a3", 16),
                        UnsignedBytes.parseUnsignedByte("9e", 16),
                        UnsignedBytes.parseUnsignedByte("81", 16),
                        UnsignedBytes.parseUnsignedByte("f3", 16),
                        UnsignedBytes.parseUnsignedByte("d7", 16),
                        UnsignedBytes.parseUnsignedByte("fb", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("7c", 16),
                        UnsignedBytes.parseUnsignedByte("e3", 16),
                        UnsignedBytes.parseUnsignedByte("39", 16),
                        UnsignedBytes.parseUnsignedByte("82", 16),
                        UnsignedBytes.parseUnsignedByte("9b", 16),
                        UnsignedBytes.parseUnsignedByte("2f", 16),
                        UnsignedBytes.parseUnsignedByte("ff", 16),
                        UnsignedBytes.parseUnsignedByte("87", 16),
                        UnsignedBytes.parseUnsignedByte("34", 16),
                        UnsignedBytes.parseUnsignedByte("8e", 16),
                        UnsignedBytes.parseUnsignedByte("43", 16),
                        UnsignedBytes.parseUnsignedByte("44", 16),
                        UnsignedBytes.parseUnsignedByte("c4", 16),
                        UnsignedBytes.parseUnsignedByte("de", 16),
                        UnsignedBytes.parseUnsignedByte("e9", 16),
                        UnsignedBytes.parseUnsignedByte("cb", 16)

                },
                {
                        UnsignedBytes.parseUnsignedByte("54", 16),
                        UnsignedBytes.parseUnsignedByte("7b", 16),
                        UnsignedBytes.parseUnsignedByte("94", 16),
                        UnsignedBytes.parseUnsignedByte("32", 16),
                        UnsignedBytes.parseUnsignedByte("a6", 16),
                        UnsignedBytes.parseUnsignedByte("c2", 16),
                        UnsignedBytes.parseUnsignedByte("23", 16),
                        UnsignedBytes.parseUnsignedByte("3d", 16),
                        UnsignedBytes.parseUnsignedByte("ee", 16),
                        UnsignedBytes.parseUnsignedByte("4c", 16),
                        UnsignedBytes.parseUnsignedByte("95", 16),
                        UnsignedBytes.parseUnsignedByte("0b", 16),
                        UnsignedBytes.parseUnsignedByte("42", 16),
                        UnsignedBytes.parseUnsignedByte("fa", 16),
                        UnsignedBytes.parseUnsignedByte("c3", 16),
                        UnsignedBytes.parseUnsignedByte("4e", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("08", 16),
                        UnsignedBytes.parseUnsignedByte("2e", 16),
                        UnsignedBytes.parseUnsignedByte("a1", 16),
                        UnsignedBytes.parseUnsignedByte("66", 16),
                        UnsignedBytes.parseUnsignedByte("28", 16),
                        UnsignedBytes.parseUnsignedByte("d9", 16),
                        UnsignedBytes.parseUnsignedByte("24", 16),
                        UnsignedBytes.parseUnsignedByte("b2", 16),
                        UnsignedBytes.parseUnsignedByte("76", 16),
                        UnsignedBytes.parseUnsignedByte("5b", 16),
                        UnsignedBytes.parseUnsignedByte("a2", 16),
                        UnsignedBytes.parseUnsignedByte("49", 16),
                        UnsignedBytes.parseUnsignedByte("6d", 16),
                        UnsignedBytes.parseUnsignedByte("8b", 16),
                        UnsignedBytes.parseUnsignedByte("d1", 16),
                        UnsignedBytes.parseUnsignedByte("25", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("72", 16),
                        UnsignedBytes.parseUnsignedByte("f8", 16),
                        UnsignedBytes.parseUnsignedByte("f6", 16),
                        UnsignedBytes.parseUnsignedByte("64", 16),
                        UnsignedBytes.parseUnsignedByte("86", 16),
                        UnsignedBytes.parseUnsignedByte("68", 16),
                        UnsignedBytes.parseUnsignedByte("98", 16),
                        UnsignedBytes.parseUnsignedByte("16", 16),
                        UnsignedBytes.parseUnsignedByte("d4", 16),
                        UnsignedBytes.parseUnsignedByte("a4", 16),
                        UnsignedBytes.parseUnsignedByte("5c", 16),
                        UnsignedBytes.parseUnsignedByte("cc", 16),
                        UnsignedBytes.parseUnsignedByte("5d", 16),
                        UnsignedBytes.parseUnsignedByte("65", 16),
                        UnsignedBytes.parseUnsignedByte("b6", 16),
                        UnsignedBytes.parseUnsignedByte("92", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("6c", 16),
                        UnsignedBytes.parseUnsignedByte("70", 16),
                        UnsignedBytes.parseUnsignedByte("48", 16),
                        UnsignedBytes.parseUnsignedByte("50", 16),
                        UnsignedBytes.parseUnsignedByte("fd", 16),
                        UnsignedBytes.parseUnsignedByte("ed", 16),
                        UnsignedBytes.parseUnsignedByte("b9", 16),
                        UnsignedBytes.parseUnsignedByte("da", 16),
                        UnsignedBytes.parseUnsignedByte("5e", 16),
                        UnsignedBytes.parseUnsignedByte("15", 16),
                        UnsignedBytes.parseUnsignedByte("46", 16),
                        UnsignedBytes.parseUnsignedByte("57", 16),
                        UnsignedBytes.parseUnsignedByte("a7", 16),
                        UnsignedBytes.parseUnsignedByte("8d", 16),
                        UnsignedBytes.parseUnsignedByte("9d", 16),
                        UnsignedBytes.parseUnsignedByte("84", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("90", 16),
                        UnsignedBytes.parseUnsignedByte("d8", 16),
                        UnsignedBytes.parseUnsignedByte("ab", 16),
                        UnsignedBytes.parseUnsignedByte("00", 16),
                        UnsignedBytes.parseUnsignedByte("8c", 16),
                        UnsignedBytes.parseUnsignedByte("bc", 16),
                        UnsignedBytes.parseUnsignedByte("d3", 16),
                        UnsignedBytes.parseUnsignedByte("0a", 16),
                        UnsignedBytes.parseUnsignedByte("f7", 16),
                        UnsignedBytes.parseUnsignedByte("e4", 16),
                        UnsignedBytes.parseUnsignedByte("58", 16),
                        UnsignedBytes.parseUnsignedByte("05", 16),
                        UnsignedBytes.parseUnsignedByte("b8", 16),
                        UnsignedBytes.parseUnsignedByte("b3", 16),
                        UnsignedBytes.parseUnsignedByte("45", 16),
                        UnsignedBytes.parseUnsignedByte("06", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("d0", 16),
                        UnsignedBytes.parseUnsignedByte("2c", 16),
                        UnsignedBytes.parseUnsignedByte("1e", 16),
                        UnsignedBytes.parseUnsignedByte("8f", 16),
                        UnsignedBytes.parseUnsignedByte("ca", 16),
                        UnsignedBytes.parseUnsignedByte("3f", 16),
                        UnsignedBytes.parseUnsignedByte("0f", 16),
                        UnsignedBytes.parseUnsignedByte("02", 16),
                        UnsignedBytes.parseUnsignedByte("c1", 16),
                        UnsignedBytes.parseUnsignedByte("af", 16),
                        UnsignedBytes.parseUnsignedByte("bd", 16),
                        UnsignedBytes.parseUnsignedByte("03", 16),
                        UnsignedBytes.parseUnsignedByte("01", 16),
                        UnsignedBytes.parseUnsignedByte("13", 16),
                        UnsignedBytes.parseUnsignedByte("8a", 16),
                        UnsignedBytes.parseUnsignedByte("6b", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("3a", 16),
                        UnsignedBytes.parseUnsignedByte("91", 16),
                        UnsignedBytes.parseUnsignedByte("11", 16),
                        UnsignedBytes.parseUnsignedByte("41", 16),
                        UnsignedBytes.parseUnsignedByte("4f", 16),
                        UnsignedBytes.parseUnsignedByte("67", 16),
                        UnsignedBytes.parseUnsignedByte("dc", 16),
                        UnsignedBytes.parseUnsignedByte("ea", 16),
                        UnsignedBytes.parseUnsignedByte("97", 16),
                        UnsignedBytes.parseUnsignedByte("f2", 16),
                        UnsignedBytes.parseUnsignedByte("cf", 16),
                        UnsignedBytes.parseUnsignedByte("ce", 16),
                        UnsignedBytes.parseUnsignedByte("f0", 16),
                        UnsignedBytes.parseUnsignedByte("b4", 16),
                        UnsignedBytes.parseUnsignedByte("e6", 16),
                        UnsignedBytes.parseUnsignedByte("73", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("96", 16),
                        UnsignedBytes.parseUnsignedByte("ac", 16),
                        UnsignedBytes.parseUnsignedByte("74", 16),
                        UnsignedBytes.parseUnsignedByte("22", 16),
                        UnsignedBytes.parseUnsignedByte("e7", 16),
                        UnsignedBytes.parseUnsignedByte("ad", 16),
                        UnsignedBytes.parseUnsignedByte("35", 16),
                        UnsignedBytes.parseUnsignedByte("85", 16),
                        UnsignedBytes.parseUnsignedByte("e2", 16),
                        UnsignedBytes.parseUnsignedByte("f9", 16),
                        UnsignedBytes.parseUnsignedByte("37", 16),
                        UnsignedBytes.parseUnsignedByte("e8", 16),
                        UnsignedBytes.parseUnsignedByte("1c", 16),
                        UnsignedBytes.parseUnsignedByte("75", 16),
                        UnsignedBytes.parseUnsignedByte("df", 16),
                        UnsignedBytes.parseUnsignedByte("6e", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("47", 16),
                        UnsignedBytes.parseUnsignedByte("f1", 16),
                        UnsignedBytes.parseUnsignedByte("1a", 16),
                        UnsignedBytes.parseUnsignedByte("71", 16),
                        UnsignedBytes.parseUnsignedByte("1d", 16),
                        UnsignedBytes.parseUnsignedByte("29", 16),
                        UnsignedBytes.parseUnsignedByte("c5", 16),
                        UnsignedBytes.parseUnsignedByte("89", 16),
                        UnsignedBytes.parseUnsignedByte("6f", 16),
                        UnsignedBytes.parseUnsignedByte("b7", 16),
                        UnsignedBytes.parseUnsignedByte("62", 16),
                        UnsignedBytes.parseUnsignedByte("0e", 16),
                        UnsignedBytes.parseUnsignedByte("aa", 16),
                        UnsignedBytes.parseUnsignedByte("18", 16),
                        UnsignedBytes.parseUnsignedByte("be", 16),
                        UnsignedBytes.parseUnsignedByte("1b", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("fc", 16),
                        UnsignedBytes.parseUnsignedByte("56", 16),
                        UnsignedBytes.parseUnsignedByte("3e", 16),
                        UnsignedBytes.parseUnsignedByte("4b", 16),
                        UnsignedBytes.parseUnsignedByte("c6", 16),
                        UnsignedBytes.parseUnsignedByte("d2", 16),
                        UnsignedBytes.parseUnsignedByte("79", 16),
                        UnsignedBytes.parseUnsignedByte("20", 16),
                        UnsignedBytes.parseUnsignedByte("9a", 16),
                        UnsignedBytes.parseUnsignedByte("db", 16),
                        UnsignedBytes.parseUnsignedByte("c0", 16),
                        UnsignedBytes.parseUnsignedByte("fe", 16),
                        UnsignedBytes.parseUnsignedByte("78", 16),
                        UnsignedBytes.parseUnsignedByte("cd", 16),
                        UnsignedBytes.parseUnsignedByte("5a", 16),
                        UnsignedBytes.parseUnsignedByte("f4", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("1f", 16),
                        UnsignedBytes.parseUnsignedByte("dd", 16),
                        UnsignedBytes.parseUnsignedByte("a8", 16),
                        UnsignedBytes.parseUnsignedByte("33", 16),
                        UnsignedBytes.parseUnsignedByte("88", 16),
                        UnsignedBytes.parseUnsignedByte("07", 16),
                        UnsignedBytes.parseUnsignedByte("c7", 16),
                        UnsignedBytes.parseUnsignedByte("31", 16),
                        UnsignedBytes.parseUnsignedByte("b1", 16),
                        UnsignedBytes.parseUnsignedByte("12", 16),
                        UnsignedBytes.parseUnsignedByte("10", 16),
                        UnsignedBytes.parseUnsignedByte("59", 16),
                        UnsignedBytes.parseUnsignedByte("27", 16),
                        UnsignedBytes.parseUnsignedByte("80", 16),
                        UnsignedBytes.parseUnsignedByte("ec", 16),
                        UnsignedBytes.parseUnsignedByte("5f", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("60", 16),
                        UnsignedBytes.parseUnsignedByte("51", 16),
                        UnsignedBytes.parseUnsignedByte("7f", 16),
                        UnsignedBytes.parseUnsignedByte("a9", 16),
                        UnsignedBytes.parseUnsignedByte("19", 16),
                        UnsignedBytes.parseUnsignedByte("b5", 16),
                        UnsignedBytes.parseUnsignedByte("4a", 16),
                        UnsignedBytes.parseUnsignedByte("0d", 16),
                        UnsignedBytes.parseUnsignedByte("2d", 16),
                        UnsignedBytes.parseUnsignedByte("e5", 16),
                        UnsignedBytes.parseUnsignedByte("7a", 16),
                        UnsignedBytes.parseUnsignedByte("9f", 16),
                        UnsignedBytes.parseUnsignedByte("93", 16),
                        UnsignedBytes.parseUnsignedByte("c9", 16),
                        UnsignedBytes.parseUnsignedByte("9c", 16),
                        UnsignedBytes.parseUnsignedByte("ef", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("a0", 16),
                        UnsignedBytes.parseUnsignedByte("e0", 16),
                        UnsignedBytes.parseUnsignedByte("3b", 16),
                        UnsignedBytes.parseUnsignedByte("4d", 16),
                        UnsignedBytes.parseUnsignedByte("ae", 16),
                        UnsignedBytes.parseUnsignedByte("2a", 16),
                        UnsignedBytes.parseUnsignedByte("f5", 16),
                        UnsignedBytes.parseUnsignedByte("b0", 16),
                        UnsignedBytes.parseUnsignedByte("c8", 16),
                        UnsignedBytes.parseUnsignedByte("eb", 16),
                        UnsignedBytes.parseUnsignedByte("bb", 16),
                        UnsignedBytes.parseUnsignedByte("3c", 16),
                        UnsignedBytes.parseUnsignedByte("83", 16),
                        UnsignedBytes.parseUnsignedByte("53", 16),
                        UnsignedBytes.parseUnsignedByte("99", 16),
                        UnsignedBytes.parseUnsignedByte("61", 16)
                },
                {
                        UnsignedBytes.parseUnsignedByte("17", 16),
                        UnsignedBytes.parseUnsignedByte("2b", 16),
                        UnsignedBytes.parseUnsignedByte("04", 16),
                        UnsignedBytes.parseUnsignedByte("7e", 16),
                        UnsignedBytes.parseUnsignedByte("ba", 16),
                        UnsignedBytes.parseUnsignedByte("77", 16),
                        UnsignedBytes.parseUnsignedByte("d6", 16),
                        UnsignedBytes.parseUnsignedByte("26", 16),
                        UnsignedBytes.parseUnsignedByte("e1", 16),
                        UnsignedBytes.parseUnsignedByte("69", 16),
                        UnsignedBytes.parseUnsignedByte("14", 16),
                        UnsignedBytes.parseUnsignedByte("63", 16),
                        UnsignedBytes.parseUnsignedByte("55", 16),
                        UnsignedBytes.parseUnsignedByte("21", 16),
                        UnsignedBytes.parseUnsignedByte("0c", 16),
                        UnsignedBytes.parseUnsignedByte("7d", 16)
                }
        };
}
